#include <esp_event_base.h>

ESP_EVENT_DECLARE_BASE(BLUEWATCH_EVENTS);

typedef enum {
	BLUEWATCH_EVENT_WIFI_CONNECTING,
	BLUEWATCH_EVENT_DISABLE_SLEEP_CHANGE,
	BLUEWATCH_EVENT_BATTERY_UPDATE,
	BLUEWATCH_EVENT_VBUS_INSERT,
	BLUEWATCH_EVENT_VBUS_REMOVE,
	BLUEWATCH_EVENT_BATTERY_CHARGE_DONE,
	BLUEWATCH_EVENT_BATTERY_CHARGE_START
} bluewatch_event_id_t;
